from typing import Final

BASE_URL: Final[str] = "https://ecobici.cdmx.gob.mx/datos-abiertos/"
ROOT_FOLDER: Final[str] = "ecobici_data" # ecobici_data - ecobici_historic_csv
MONTHS_MAPPING: Final[dict] = {
    'enero': '01', 
    'febrero': '02', 
    'marzo': '03', 
    'abril': '04',
    'mayo': '05', 
    'junio': '06', 
    'julio': '07', 
    'agosto': '08',
    'septiembre': '09', 
    'octubre': '10', 
    'noviembre': '11', 
    'diciembre': '12',
    'ene': '01', 
    'feb': '02', 
    'mar': '03', 
    'abr': '04',
    'may': '05', 
    'jun': '06', 
    'jul': '07', 
    'ago': '08',
    'sep': '09', 
    'oct': '10', 
    'nov': '11', 
    'dic': '12',
    'jan': '01', 
    'feb': '02', 
    'mar': '03', 
    'apr': '04',
    'may': '05', 
    'jun': '06', 
    'jul': '07', 
    'aug': '08',
    'sep': '09', 
    'oct': '10', 
    'nov': '11', 
    'dec': '12'
}